### PR TITLE
feat: support Apisix ingress trafficrouting

### PR DESCRIPTION
**Pull request by fatpa**
### Ⅰ. Describe what this PR does
Add Apisix Ingress into TrafficRouting module.

### Ⅱ. Does this pull request fix one issue?

NONE.

### Ⅲ. Special notes for reviews
Using `ApisixRoute` and `ApisixUpstream` CRD instead of Ingress class.

### CODE REVIEW

**Comment by zmberg** [comment]
@fatpa It's great that you're able to expand the capabilities of rollout, something we've always wanted. But there are some things I want to chat with you again. I wonder if you are in the Kruise community group?

**Comment by fatpa** [comment]
> 

No, I'm not in the group. Could you tell me which app or group channel I can find it?

**Comment by zmberg** [comment]
Can you join Dingding Group 23330762 ?

**Comment by fatpa** [comment]
> Can you join Dingding Group 23330762 ?

I'm in the group now.

**Pull request closed without merging**
