### PR TITLE
update tutorial to support minikube in mac m1

### PR DESCRIPTION
**Pull request by xiao-jay**
Signed-off-by: 晓杰 <2561589453@qq.com>

Ⅰ. Describe what this PR does
doc incomplete
1、update tutorial to support minikube in mac m1，add image can test in m1
2、fix error traffic number in photo

Ⅱ. Does this pull request fix one issue?
fix https://github.com/openkruise/rollouts/issues/30

### CODE REVIEW

**Comment by xiao-jay** [comment]
@FillZpp 
i have sign my commit,Could you please review my commit if you have free?

**Comment by FillZpp** [comment]
/approve
Thanks!

**Pull request merged**
