### PR TITLE
update rollout types in basic_usage

### PR DESCRIPTION
**Pull request by Chenxi-Seu**
### Ⅰ. Describe what this PR does
1. Update Rollout type in doc basic_usage for the types had been deleted in Rollout CRD.

### Ⅱ. Does this pull request fix one issue?

None

### CODE REVIEW

**Comment by xiao-jay** [comment]
lgtm，It is true that these types are not in the source code, which will cause an erro.
By the way ，please sign your commit

**Comment by Chenxi-Seu** [comment]
> 

Thanks, done.

**Comment by xiao-jay** [comment]
@veophi @FillZpp please review this simple pr

**Review by FillZpp — APPROVED** [review]
/lgtm
thanks @Chenxi-Seu @xiao-jay

**Pull request merged**
